- name: Hello world
  #hosts: web
  hosts: local
  tasks:
  - name: Print hello world
    ansible.builtin.debug:
      msg: "Hello world"

- name: Play-2
  hosts: local
  become: yes
  tasks:
  - name: Play-2 and task 1
    ansible.builtin.debug:
      msg: "Hello from Play-2 and task1"          